name: muriisa
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  cupertino_icons: "^1.0.2"
  http: ^0.13.4
  youtube_player_flutter: ^8.1.0
  animations: ^2.0.3
  audioplayers: ^0.20.1
  percent_indicator: ^4.2.3
  webview_flutter: ^4.8.0
  share_plus: ^8.0.0
  flutter_audio_waveforms: ^1.0.0
  audio_waveforms: ^1.0.5
  
 
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/Whats.jpeg
    - assets/share.png
    - assets/gloryfm-1-9rh.png
    - assets/WhatsApp Image 2023-11-06 at 5.14.46 PM.jpeg
    - assets/church .png
    - assets/sound-waves.png
    - assets/1.jpeg
    - assets/2.jpeg
    - assets/3.jpeg
    - assets/4.jpeg
    - assets/HE HEALS.jpeg
    - assets/OIP.jpeg
    - assets/Copy.png
  #  - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
 
